<a href="https://colab.research.google.com/github/ANJANAMB1/Data-science/blob/main/Datasciencelab_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
print("Example for broadcasting: ")
v=np.array([1,2,3])
w=np.array([4,5])
print("v = ",v)
print("w=",w)
print("Outer product of above vectors: ")
print(np.reshape(v,(3,1))*w)
x=np.array([[1,2,3],[4,5,6]])
print("x = ",x)
print("Resultant matrix after adding the vector x to each row of matrix v: ")
print(x+v)
print("Example for broadcasting fails: ")
print("Adding the vector x to each column of matrix w will generate an error")
print("Solution: Reshape the matrix w then the result will be: ")
print(x+np.reshape(w,(2,1)))

Example for broadcasting: 
v =  [1 2 3]
w= [4 5]
Outer product of above vectors: 
[[ 4  5]
 [ 8 10]
 [12 15]]
x =  [[1 2 3]
 [4 5 6]]
Resultant matrix after adding the vector x to each row of matrix v: 
[[2 4 6]
 [5 7 9]]
Example for broadcasting fails: 
Adding the vector x to each column of matrix w will generate an error
Solution: Reshape the matrix w then the result will be: 
[[ 5  6  7]
 [ 9 10 11]]


In [3]:
import numpy as np

print("Array indexing: slicing")
a1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("a1 =", a1)

b = a1[:2, 1:3]
print("Subarray consisting of the first two rows and columns 1 and 2:", b)

b = a1[1:2, :]
print("Subarray consists of the second row:", b)

print("Accessing columns:")
c = a1[:, 1:2]
print(c, c.shape)

print("Array integer indexing:")
a2 = np.array([[1, 2], [3, 4], [5, 6]])
print("a2 =", a2)

print("Example of array integer indexing:", a2[[0, 1, 2], [0, 1, 0]])
print(a2[[0, 0], [1, 1]])
print(np.array([a2[0, 1], a2[0, 1]]))

a3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print("a3 =", a3)

# Create an array of indices
b = np.array([0, 2, 0, 1])
print("b =", b)

print("Select one element from each row of a using the indices in b:")
print("a3 =", a3[np.arange(4), b])

a3[np.arange(4), b] += 10
print("a3 =", a3)

print("Boolean array indexing:")
a = np.array([[1, 2], [3, 4], [5, 6]])
print("a =", a)

bool_idx = (a > 2)
print("Elements greater than 2:", a[bool_idx])

Array indexing: slicing
a1 = [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Subarray consisting of the first two rows and columns 1 and 2: [[2 3]
 [6 7]]
Subarray consists of the second row: [[5 6 7 8]]
Accessing columns:
[[ 2]
 [ 6]
 [10]] (3, 1)
Array integer indexing:
a2 = [[1 2]
 [3 4]
 [5 6]]
Example of array integer indexing: [1 4 5]
[2 2]
[2 2]
a3 = [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
b = [0 2 0 1]
Select one element from each row of a using the indices in b:
a3 = [ 1  6  7 11]
a3 = [[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]
Boolean array indexing:
a = [[1 2]
 [3 4]
 [5 6]]
Elements greater than 2: [3 4 5 6]
